// SPDX-FileCopyrightText: Copyright 2026 shadLauncher5 Project
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once
#include <common/types.h>

namespace Libraries::SystemService {

enum ProsperoSystemParamLanguage : s32 {
    PROSPERO_SYSTEM_PARAM_LANG_JAPANESE = 0,
    PROSPERO_SYSTEM_PARAM_LANG_ENGLISH_US = 1,
    PROSPERO_SYSTEM_PARAM_LANG_FRENCH = 2,
    PROSPERO_SYSTEM_PARAM_LANG_SPANISH = 3,
    PROSPERO_SYSTEM_PARAM_LANG_GERMAN = 4,
    PROSPERO_SYSTEM_PARAM_LANG_ITALIAN = 5,
    PROSPERO_SYSTEM_PARAM_LANG_DUTCH = 6,
    PROSPERO_SYSTEM_PARAM_LANG_PORTUGUESE_PT = 7,
    PROSPERO_SYSTEM_PARAM_LANG_RUSSIAN = 8,
    PROSPERO_SYSTEM_PARAM_LANG_KOREAN = 9,
    PROSPERO_SYSTEM_PARAM_LANG_CHINESE_T = 10,
    PROSPERO_SYSTEM_PARAM_LANG_CHINESE_S = 11,
    PROSPERO_SYSTEM_PARAM_LANG_FINNISH = 12,
    PROSPERO_SYSTEM_PARAM_LANG_SWEDISH = 13,
    PROSPERO_SYSTEM_PARAM_LANG_DANISH = 14,
    PROSPERO_SYSTEM_PARAM_LANG_NORWEGIAN = 15,
    PROSPERO_SYSTEM_PARAM_LANG_POLISH = 16,
    PROSPERO_SYSTEM_PARAM_LANG_PORTUGUESE_BR = 17,
    PROSPERO_SYSTEM_PARAM_LANG_ENGLISH_GB = 18,
    PROSPERO_SYSTEM_PARAM_LANG_TURKISH = 19,
    PROSPERO_SYSTEM_PARAM_LANG_SPANISH_LA = 20,
    PROSPERO_SYSTEM_PARAM_LANG_ARABIC = 21,
    PROSPERO_SYSTEM_PARAM_LANG_FRENCH_CA = 22,
    PROSPERO_SYSTEM_PARAM_LANG_CZECH = 23,
    PROSPERO_SYSTEM_PARAM_LANG_HUNGARIAN = 24,
    PROSPERO_SYSTEM_PARAM_LANG_GREEK = 25,
    PROSPERO_SYSTEM_PARAM_LANG_ROMANIAN = 26,
    PROSPERO_SYSTEM_PARAM_LANG_THAI = 27,
    PROSPERO_SYSTEM_PARAM_LANG_VIETNAMESE = 28,
    PROSPERO_SYSTEM_PARAM_LANG_INDONESIAN = 29,
    PROSPERO_SYSTEM_PARAM_LANG_UKRAINIAN = 30,
};

} // namespace Libraries::SystemService